<a href="https://colab.research.google.com/github/arnav-007/newcodingbot/blob/main/rock_vs_Mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
sonar_data = pd.read_csv('/Copy of sonar data.csv', header=None, encoding= 'unicode_escape')

In [ ]:
sonar_data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [ ]:
sonar_data.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [ ]:
sonar_data[0].unique()

array([0.02  , 0.0453, 0.0262, 0.01  , 0.0762, 0.0286, 0.0317, 0.0519,
       0.0223, 0.0164, 0.0039, 0.0123, 0.0079, 0.009 , 0.0124, 0.0298,
       0.0352, 0.0192, 0.027 , 0.0126, 0.0473, 0.0664, 0.0099, 0.0115,
       0.0293, 0.0201, 0.0151, 0.0177, 0.0189, 0.024 , 0.0084, 0.0195,
       0.0442, 0.0311, 0.0206, 0.0094, 0.0333, 0.0091, 0.0068, 0.0093,
       0.0211, 0.0257, 0.0408, 0.0308, 0.0373, 0.019 , 0.0119, 0.0353,
       0.0131, 0.0087, 0.0132, 0.0152, 0.0216, 0.0225, 0.0125, 0.013 ,
       0.0135, 0.0086, 0.0067, 0.0071, 0.0176, 0.0265, 0.0368, 0.0065,
       0.0036, 0.0208, 0.0139, 0.0109, 0.0202, 0.0239, 0.0336, 0.0231,
       0.0108, 0.0229, 0.0409, 0.0217, 0.0378, 0.0365, 0.0188, 0.0856,
       0.0274, 0.0235, 0.0253, 0.026 , 0.0459, 0.0025, 0.0291, 0.0181,
       0.0491, 0.1313, 0.0629, 0.0335, 0.0587, 0.0162, 0.0307, 0.0116,
       0.0331, 0.0428, 0.0599, 0.0264, 0.021 , 0.053 , 0.0454, 0.0283,
       0.0114, 0.0414, 0.0228, 0.0363, 0.0261, 0.0346, 0.0249, 0.0388,
       0.0715, 0.0209, 0.0374, 0.1371, 0.0443, 0.115 , 0.0968, 0.079 ,
       0.1083, 0.1088, 0.043 , 0.0731, 0.0412, 0.0707, 0.0526, 0.0516,
       0.0299, 0.0721, 0.1021, 0.0654, 0.0712, 0.0207, 0.0233, 0.0117,
       0.0047, 0.0107, 0.0258, 0.0305, 0.0072, 0.0163, 0.0221, 0.0411,
       0.0137, 0.0015, 0.0134, 0.0179, 0.018 , 0.0329, 0.0191, 0.0294,
       0.0635, 0.0197, 0.0394, 0.031 , 0.0423, 0.0095, 0.0096, 0.0269,
       0.034 , 0.0089, 0.0158, 0.0156, 0.0315, 0.0056, 0.0203, 0.0392,
       0.0129, 0.005 , 0.0366, 0.0238, 0.0272, 0.0187, 0.0323, 0.0522,
       0.0303])

In [ ]:
sonar_data[12].value_counts()

0.2657    3
0.2624    2
0.2863    2
0.2301    2
0.3141    2
         ..
0.0493    1
0.1546    1
0.1254    1
0.1499    1
0.1665    1
Name: 12, Length: 198, dtype: int64

In [ ]:
sonar_data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
12,,,,,,,,,,,,,,,,,,,,,
0.0184,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
0.0252,0.0291,0.0400,0.0771,0.0809,0.0521,0.1051,0.0145,0.0674,0.1294,0.1146,...,0.0000,0.0056,0.0237,0.0204,0.0050,0.0137,0.0164,0.0081,0.0139,0.0111
0.0309,0.0091,0.0213,0.0206,0.0505,0.0657,0.0795,0.0970,0.0872,0.0743,0.0837,...,0.0300,0.0112,0.0112,0.0102,0.0026,0.0097,0.0098,0.0043,0.0071,0.0108
0.0493,0.0139,0.0222,0.0089,0.0108,0.0215,0.0136,0.0659,0.0954,0.0786,0.1015,...,0.0024,0.0062,0.0072,0.0113,0.0012,0.0022,0.0025,0.0059,0.0039,0.0048
0.0513,0.0317,0.0956,0.1321,0.1408,0.1674,0.1710,0.0731,0.1401,0.2083,0.3513,...,0.0195,0.0201,0.0248,0.0131,0.0070,0.0138,0.0092,0.0143,0.0036,0.0103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.6173,0.0443,0.0446,0.0235,0.1008,0.2252,0.2611,0.2061,0.1668,0.1801,0.3083,...,0.0248,0.0274,0.0205,0.0141,0.0185,0.0055,0.0045,0.0115,0.0152,0.0100
0.6343,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0104,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062
0.6919,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
0.7022,0.0335,0.0134,0.0696,0.1180,0.0348,0.1180,0.1948,0.1607,0.3036,0.4372,...,0.0302,0.0244,0.0232,0.0093,0.0159,0.0193,0.0032,0.0377,0.0126,0.0156
0.7131,0.1371,0.1226,0.1385,0.1484,0.1776,0.1428,0.1773,0.2161,0.1630,0.2067,...,0.0171,0.0118,0.0129,0.0344,0.0065,0.0067,0.0022,0.0079,0.0146,0.0051

In [ ]:
x = sonar_data.drop(columns=60, axis=1)
y = sonar_data[60]

In [ ]:
print(x)
print(y)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

         57      58      59
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
203  0.0115  0.0193  0.0157
204  0.0032  0.0062  0.0067
205  0.0138  0.0077  0.0031
206  0.0079  0.0036  0.0048
207  0.0036  0.0061  0.0115

[208 rows x 60 columns]
0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

test and train data

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(208, 60) (187, 60) (21, 60)

In [ ]:
print(x_train)
print(y_train)

         0       1       2       3       4       5       6       7       8   \
144  0.0299  0.0688  0.0992  0.1021  0.0800  0.0629  0.0130  0.0813  0.1761
35   0.0206  0.0132  0.0533  0.0569  0.0647  0.1432  0.1344  0.2041  0.1571
143  0.0516  0.0944  0.0622  0.0415  0.0995  0.2431  0.1777  0.2018  0.2611
53   0.0293  0.0378  0.0257  0.0062  0.0130  0.0612  0.0895  0.1107  0.0973
6    0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
43   0.0093  0.0269  0.0217  0.0339  0.0305  0.1172  0.1450  0.0638  0.0740
22   0.0099  0.0484  0.0299  0.0297  0.0652  0.1077  0.2363  0.2385  0.0075
72   0.0208  0.0186  0.0131  0.0211  0.0610  0.0613  0.0612  0.0506  0.0989
15   0.0298  0.0615  0.0650  0.0921  0.1615  0.2294  0.2176  0.2033  0.1459
168  0.0015  0.0186  0.0289  0.0195  0.0515  0.0817  0.1005  0.0124  0.1168

         9   ...      50      51      52      53      54      55      56  \
144  0.0998  ...  0.0342  0.0459  0.0277  0.0172  0.0087  0.0046  0.0203
35   0.1573  ...  0.0307  0.0386  0.0147  0.0018  0.0100  0.0096  0.0077
143  0.1294  ...  0.0456  0.0432  0.0274  0.0152  0.0120  0.0129  0.0020
53   0.0751  ...  0.0076  0.0065  0.0072  0.0108  0.0051  0.0102  0.0041
6    0.3513  ...  0.0195  0.0201  0.0248  0.0131  0.0070  0.0138  0.0092
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
43   0.1360  ...  0.0309  0.0212  0.0091  0.0056  0.0086  0.0092  0.0070
22   0.1882  ...  0.0396  0.0173  0.0149  0.0115  0.0202  0.0139  0.0029
72   0.1093  ...  0.0140  0.0074  0.0063  0.0081  0.0087  0.0044  0.0028
15   0.0852  ...  0.0154  0.0031  0.0153  0.0071  0.0212  0.0076  0.0152
168  0.1476  ...  0.0045  0.0108  0.0075  0.0089  0.0036  0.0029  0.0013

         57      58      59
144  0.0130  0.0115  0.0015
35   0.0180  0.0109  0.0070
143  0.0109  0.0074  0.0078
53   0.0055  0.0050  0.0087
6    0.0143  0.0036  0.0103
..      ...     ...     ...
43   0.0116  0.0060  0.0110
22   0.0160  0.0106  0.0134
72   0.0019  0.0049  0.0023
15   0.0049  0.0200  0.0073
168  0.0010  0.0032  0.0047

[187 rows x 60 columns]
144    M
35     R
143    M
53     R
6      R
      ..
43     R
22     R
72     R
15     R
168    M
Name: 60, Length: 187, dtype: object

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train, y_train)

LogisticRegression()

model evluation

In [ ]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [ ]:
print('accuracy of trining data', training_data_accuracy)

accuracy of trining data 0.8235294117647058

In [ ]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [ ]:
print('accuracy of test data', test_data_accuracy)

accuracy of test data 0.8571428571428571

making a predictive system

In [ ]:
input_data = ( 0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.0660,0.2273,0.3100,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.5550,0.6711,0.6415,0.7104,0.8080,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.0510,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032)

# changing the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the np array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
  print('the object is rock')
else:
    print('the object is mine')

['R']
the object is rock